### PR TITLE
Don't render legend entries unless a label is provided [re #5758]

### PR DESCRIPTION
**Pull request by choochburger**
Python API users would like legend items to not be generated for a plot when `legend_label` is set to `null`. From our docs:

```
legend_label (str) – A string label to be used in the legend. If unspecified, this plot will not appear in the legend.
```

### CODE REVIEW

**Comment by rcreasi** [comment]
👍  Looks good.

**Comment by lshrinivas** [comment]
Looks good! Please hold on until I reset `master` to revert the unintended changes

**Comment by lshrinivas** [comment]
I've reverted the multiseries stuff from master - please rebase this branch before merging to master.

**Comment by choochburger** [comment]
@lshrinivas thanks for splitting that stuff off. Going to add a quick integration test to the main repo and then I'll merge this.

**Pull request merged**
