### PR TITLE
Support overriding the type of D3 scale used for a data series' axis

### PR DESCRIPTION
**Pull request by nawatts**

### CODE REVIEW

**Review by nickdoesdesign — APPROVED** [review]
Looks great. I think we totally forgot about const when we fist started this, so Im glad to see it get added.

**Comment by rcreasi** [comment]
@nickdoesdesign You're right, there are only a handful of `const` variables in all of Nugget. I have just one thing to say to those who have fought `const` correctness and lost so badly they just don't know what to do: Sad!

**Comment by nickdoesdesign** [comment]
Make Nugget Great Again @rcreasi

**Review by rcreasi — APPROVED** [review]

**Comment by choochburger** [comment]
@rcreasi @nickdoesdesign we also almost completely neglected `let` during initial development, too. Gotta get with the times! 🤣 

These changes look super solid 👍

**Review by choochburger — APPROVED** [review]

**Pull request merged**
