### PR TITLE
Tweak position of axis label so it doesn't spill outside SVG element.

### PR DESCRIPTION
**Pull request by lshrinivas**
Plus, IE doesn't support dominant-baseline, so compensate for it

### CODE REVIEW

**Comment by lshrinivas** [comment]
This needs a couple test updates too - brb

**Comment by nickdoesdesign** [comment]
Looks good. Just update the tests and you are free to merge.

**Comment by lshrinivas** [comment]
Updated test too! Merging

**Comment by choochburger** [comment]
Fantastic :+1: It might be useful to still put Assembla ticket refs in these PR titles so we have a common point of reference between this and our internal apps (even if the POST hook isn't working yet).

**Pull request merged**
